name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Running common workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo username is ${{ inputs.username }} and token is ${{ secrets.token }}